### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by sqs** [casualjim/vscode-theme-desertex#3]
@lubronzhan asked us to allow users to use this theme on [Sourcegraph](https://sourcegraph.com). If that's OK with you, could you please add a license to this repository so we can do so? Thanks!

**Comment by casualjim** [comment]
I added the license file

**Comment by sqs** [comment]
Thanks!

**Comment by casualjim** [comment]
so should I expect to be able to use this in sourcegraph soon?
